## QF620 Final Project: SPX Options During the 2025 Liberation Day Tariff Shock
Objective

```
Understand how market expectations, left-tail risk, and geopolitical retaliation
are priced dynamically, in real-time, by high-frequency SPX options and ES
futures market data.
```

In [2]:
# Initiate all libraries
import os
import numpy as np
import pandas as pd

## Pull in CSV file

In [26]:
ASSET = pd.DataFrame()
OPTION_CALL_BID = pd.DataFrame()
OPTION_CALL_ASK = pd.DataFrame()
OPTION_PUT_BID = pd.DataFrame()
OPTION_PUT_ASK = pd.DataFrame()

for file in os.listdir("ETH"):
    if file.endswith("assets.csv"):
        ASSET = pd.concat([ASSET, pd.read_csv(os.path.join("ETH", file), index_col=0)])
        ASSET["TRADING_HOUR"] = 'ETH'
    elif file.find("call_bid") > 0:
        OPTION_CALL_BID = pd.concat([OPTION_CALL_BID, pd.read_csv(os.path.join("ETH", file), index_col=0)])
    elif file.find("call_ask") > 0:
        OPTION_CALL_ASK = pd.concat([OPTION_CALL_ASK, pd.read_csv(os.path.join("ETH", file), index_col=0)])
    elif file.find("put_bid") > 0:
        OPTION_PUT_BID = pd.concat([OPTION_PUT_BID, pd.read_csv(os.path.join("ETH", file), index_col=0)])
    elif file.find("put_ask") > 0:
        OPTION_PUT_ASK = pd.concat([OPTION_PUT_ASK, pd.read_csv(os.path.join("ETH", file), index_col=0)])

data = {
    "ASSET": ASSET,
    "OPTION_CALL_BID": OPTION_CALL_BID,
    "OPTION_CALL_ASK": OPTION_CALL_ASK,
    "OPTION_PUT_BID": OPTION_PUT_BID,
    "OPTION_PUT_ASK": OPTION_PUT_ASK
}
for df_name, df in data.items():
    # Configure each DataFrame's index
    df.index.name = "DATETIME"
    df.index = pd.to_datetime(df.index)
    df.sort_index(inplace=True)
    print(f"\nDataFrame {df_name} has shape {df.shape} and index range {df.index.min()} to {df.index.max()}")
    display(df)

DataFrame ASSET has shape (106496, 5) and index range 2025-04-01 20:15:21.924268 to 2025-04-11 09:14:58.970700

                                 SPX   ES_BID   ES_ASK    VIX TRADING_HOUR
DATETIME
2025-04-01 20:15:21.924268   5630.32   5671.5   5672.0  21.77          ETH
2025-04-01 20:15:24.955344   5630.32   5671.5   5672.0  21.77          ETH
2025-04-01 20:15:27.986076  5630.695   5672.0  5672.25  21.77          ETH
2025-04-01 20:15:30.992653  5630.945  5672.25   5672.5  21.77          ETH
2025-04-01 20:15:34.026633  5631.195   5672.5  5672.75  21.77          ETH
...                              ...      ...      ...    ...          ...
2025-04-11 09:14:46.807862  5243.925  5277.75   5278.0  44.77          ETH
2025-04-11 09:14:49.846746  5244.425  5278.25   5278.5  44.77          ETH
2025-04-11 09:14:52.887237    5242.3   5276.0   5276.5  44.77          ETH
2025-04-11 09:14:55.934802   5242.55  5276.25  5276.75  44.77          ETH
2025-04-11 09:14:58.970700   5242.55  5276.25  5276.75  44.77          ETH

[106496 rows x 5 columns]

DataFrame OPTION_CALL_BID has shape (106496, 81) and index range 2025-04-01 20:15:21.924268 to 2025-04-11 09:14:58.970700

,4600.0,4625.0,4650.0,4675.0,4700.0,4725.0,4750.0,4775.0,4800.0,4825.0,...,6375.0,6400.0,6425.0,6450.0,6475.0,6500.0,6525.0,6550.0,6575.0,6600.0
DATETIME,,,,,,,,,,,,,,,,,,,,,
2025-04-01 20:15:21.924268,1034.2,1009.4,984.5,959.7,934.9,910.1,885.2,860.4,835.6,810.9,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2025-04-01 20:15:24.955344,1034.2,1009.4,984.5,959.7,934.9,910.1,885.2,860.4,835.6,810.9,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2025-04-01 20:15:27.986076,1034.2,1009.4,984.5,959.7,934.9,910.1,885.2,860.7,835.6,810.9,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2025-04-01 20:15:30.992653,1034.5,1009.7,984.8,959.7,935.1,910.4,885.6,860.7,835.6,811.1,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2025-04-01 20:15:34.026633,1035.1,1010.2,985.4,960.6,935.7,910.9,886.1,861.3,836.5,811.7,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11 09:14:46.807862,734.9,713.3,691.8,670.5,649.3,628.3,607.5,586.8,566.3,546.0,...,0.25,0.2,0.2,0.15,0.15,0.15,0.1,0.1,0.1,0.1
2025-04-11 09:14:49.846746,734.8,713.2,691.7,670.4,649.2,628.2,607.4,586.7,566.3,546.0,...,0.25,0.2,0.2,0.15,0.15,0.15,0.1,0.1,0.1,0.1
2025-04-11 09:14:52.887237,727.4,705.7,690.0,662.9,641.9,621.0,600.3,579.7,559.4,539.2,...,0.25,0.2,0.2,0.15,0.15,0.15,0.1,0.1,0.1,0.1
2025-04-11 09:14:55.934802,733.9,712.3,690.8,669.5,648.4,627.4,606.5,585.9,565.4,545.2,...,0.25,0.2,0.2,0.15,0.15,0.15,0.1,0.1,0.1,0.1
2025-04-11 09:14:58.970700,733.7,712.1,690.6,669.3,648.2,627.2,606.4,585.7,565.3,545.0,...,0.25,0.2,0.2,0.15,0.15,0.15,0.1,0.1,0.1,0.1

DataFrame OPTION_CALL_ASK has shape (106496, 81) and index range 2025-04-01 20:15:21.924268 to 2025-04-11 09:14:58.970700

,4600.0,4625.0,4650.0,4675.0,4700.0,4725.0,4750.0,4775.0,4800.0,4825.0,...,6375.0,6400.0,6425.0,6450.0,6475.0,6500.0,6525.0,6550.0,6575.0,6600.0
DATETIME,,,,,,,,,,,,,,,,,,,,,
2025-04-01 20:15:21.924268,1045.0,1020.1,995.3,970.5,945.7,920.8,896.0,871.2,846.4,821.6,...,0.3,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.2,0.2
2025-04-01 20:15:24.955344,1045.0,1020.1,995.3,970.5,945.7,920.8,896.0,871.2,846.4,821.6,...,0.3,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.2,0.2
2025-04-01 20:15:27.986076,1045.0,1020.1,995.3,970.5,945.7,920.8,896.0,871.5,846.4,821.6,...,0.3,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.2,0.2
2025-04-01 20:15:30.992653,1045.3,1020.5,995.6,970.5,945.9,921.2,896.4,871.5,846.4,821.9,...,0.3,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.2,0.2
2025-04-01 20:15:34.026633,1045.8,1020.9,996.2,971.3,946.5,921.7,896.9,872.1,847.3,822.4,...,0.3,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.2,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11 09:14:46.807862,739.2,717.5,696.0,674.7,653.5,632.5,611.7,591.0,570.5,550.2,...,1.05,1.0,0.95,0.9,0.85,0.8,0.8,0.75,0.75,0.75
2025-04-11 09:14:49.846746,739.2,717.5,696.0,674.7,653.5,632.5,611.7,591.0,570.5,550.2,...,1.05,1.0,0.95,0.9,0.85,0.8,0.8,0.75,0.75,0.75
2025-04-11 09:14:52.887237,744.9,723.1,695.5,680.2,658.8,637.9,617.0,596.3,575.1,555.3,...,1.05,1.0,0.95,0.9,0.85,0.8,0.8,0.75,0.75,0.75
2025-04-11 09:14:55.934802,738.2,716.7,695.1,673.8,652.7,631.7,610.8,590.2,569.7,549.4,...,1.05,1.0,0.95,0.9,0.85,0.8,0.8,0.75,0.75,0.75
2025-04-11 09:14:58.970700,738.0,716.4,695.0,673.6,652.5,631.5,610.6,590.0,569.5,549.2,...,1.05,1.0,0.95,0.9,0.85,0.8,0.8,0.75,0.75,0.75

DataFrame OPTION_PUT_BID has shape (106496, 81) and index range 2025-04-01 20:15:21.924268 to 2025-04-11 09:14:58.970700

,4600.0,4625.0,4650.0,4675.0,4700.0,4725.0,4750.0,4775.0,4800.0,4825.0,...,6375.0,6400.0,6425.0,6450.0,6475.0,6500.0,6525.0,6550.0,6575.0,6600.0
DATETIME,,,,,,,,,,,,,,,,,,,,,
2025-04-01 20:15:21.924268,2.6,2.7,2.85,3.0,3.1,3.2,3.4,3.5,3.7,3.9,...,729.0,753.9,778.9,803.8,828.8,853.7,878.6,903.6,928.5,953.5
2025-04-01 20:15:24.955344,2.6,2.7,2.85,3.0,3.1,3.2,3.4,3.5,3.7,3.9,...,729.0,753.9,778.9,803.8,828.8,853.7,878.6,903.6,928.5,953.5
2025-04-01 20:15:27.986076,2.6,2.7,2.85,2.95,3.1,3.2,3.4,3.5,3.7,3.8,...,729.0,753.9,778.9,803.8,828.8,853.7,878.6,903.2,928.5,953.5
2025-04-01 20:15:30.992653,2.6,2.7,2.85,2.95,3.1,3.2,3.4,3.5,3.7,3.8,...,728.7,753.9,778.6,803.6,828.5,853.7,878.3,903.2,928.2,953.2
2025-04-01 20:15:34.026633,2.6,2.7,2.85,2.95,3.1,3.2,3.4,3.5,3.7,3.8,...,728.1,753.1,778.0,802.9,827.9,852.9,877.8,902.7,927.7,952.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11 09:14:46.807862,77.0,80.2,83.6,87.2,90.9,94.7,98.8,103.0,107.4,112.0,...,1099.7,1124.5,1149.4,1174.2,1199.1,1224.3,1248.8,1273.7,1298.5,1323.4
2025-04-11 09:14:49.846746,77.0,80.2,83.6,87.2,90.9,94.7,98.8,103.0,107.4,112.0,...,1099.7,1124.5,1149.4,1174.2,1199.1,1224.3,1248.8,1273.7,1298.5,1323.4
2025-04-11 09:14:52.887237,77.2,80.4,83.8,87.3,91.0,94.9,99.0,103.2,107.6,112.2,...,1101.5,1126.4,1151.2,1176.1,1200.9,1225.8,1250.7,1275.5,1300.4,1325.3
2025-04-11 09:14:55.934802,77.2,80.4,83.8,87.4,91.1,95.0,99.0,103.2,107.6,112.2,...,1101.3,1126.2,1151.0,1175.9,1200.7,1225.6,1250.4,1275.3,1300.2,1324.5
2025-04-11 09:14:58.970700,77.2,80.4,83.8,87.4,91.1,95.0,99.0,103.2,107.6,112.3,...,1101.3,1126.2,1151.0,1175.9,1200.7,1225.6,1250.4,1275.3,1300.2,1324.5

DataFrame OPTION_PUT_ASK has shape (106496, 81) and index range 2025-04-01 20:15:21.924268 to 2025-04-11 09:14:58.970700

,4600.0,4625.0,4650.0,4675.0,4700.0,4725.0,4750.0,4775.0,4800.0,4825.0,...,6375.0,6400.0,6425.0,6450.0,6475.0,6500.0,6525.0,6550.0,6575.0,6600.0
DATETIME,,,,,,,,,,,,,,,,,,,,,
2025-04-01 20:15:21.924268,2.85,3.0,3.1,3.3,3.4,3.5,3.7,3.8,4.0,4.1,...,739.8,764.7,789.6,814.6,839.5,864.5,889.4,914.4,939.3,964.2
2025-04-01 20:15:24.955344,2.85,3.0,3.1,3.3,3.4,3.5,3.7,3.8,4.0,4.1,...,739.8,764.7,789.6,814.6,839.5,864.5,889.4,914.4,939.3,964.2
2025-04-01 20:15:27.986076,2.85,3.0,3.1,3.3,3.4,3.5,3.7,3.8,4.0,4.1,...,739.8,764.7,789.6,814.6,839.5,864.5,889.4,914.0,939.3,964.2
2025-04-01 20:15:30.992653,2.85,3.0,3.1,3.3,3.4,3.5,3.7,3.8,4.0,4.1,...,739.4,764.7,789.4,814.3,839.3,864.5,889.1,914.0,938.9,964.0
2025-04-01 20:15:34.026633,2.85,2.95,3.1,3.3,3.4,3.5,3.7,3.8,4.0,4.1,...,738.9,763.8,788.8,813.7,838.7,863.7,888.5,913.5,938.4,963.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11 09:14:46.807862,79.7,83.0,86.4,90.0,93.7,97.6,101.7,106.0,110.4,115.0,...,1118.3,1143.2,1168.0,1192.9,1217.8,1242.6,1267.5,1292.4,1317.2,1342.1
2025-04-11 09:14:49.846746,79.7,83.0,86.4,89.9,93.7,97.6,101.7,106.0,110.4,115.0,...,1118.3,1143.2,1168.0,1192.9,1217.8,1242.6,1267.5,1292.4,1317.2,1342.1
2025-04-11 09:14:52.887237,79.7,83.0,86.4,90.0,93.8,97.7,101.8,106.1,110.6,115.3,...,1120.7,1145.1,1169.9,1195.3,1220.1,1244.5,1269.4,1294.2,1319.1,1344.0
2025-04-11 09:14:55.934802,79.7,83.0,86.4,90.0,93.8,97.7,101.8,106.1,110.6,115.3,...,1120.0,1144.8,1169.7,1194.5,1219.4,1244.3,1269.1,1294.0,1318.9,1343.8
2025-04-11 09:14:58.970700,79.7,83.0,86.4,90.0,93.8,97.7,101.8,106.1,110.6,115.3,...,1120.0,1144.8,1169.7,1194.5,1219.4,1244.3,1269.1,1294.0,1318.9,1343.8